### ISSUE TITLE
glTF prefix

### ISSUE THREAD

**Issue by philspreier** [adobe/pdf-names-list#10]
# Prefix Registration
## Developer Prefix
| Label | Value |
| ------------- | ----------- |
| Developer Prefix (4 letters) | glTF |

## Organization
| Label | Value |
| ------------- | ----------- |
| Entity/Organization Name | ISO TC 171 SC 2 |
| Address (line 1) |   |
| Address (line 2) |   |
| City, State, Zip/Postal Code |   |
| Country |  |
| Web Site/URL | https://www.iso.org/committee/53674.html |

## Person
| Label | Value |
| ------------- | ----------- |
| First Name | Betsy |
| Last Name | Fanning |
| Title | Secretary |
| Email address | betsy.fanning@3dpdfconsortium.org |

## Optional Documentation Link
| Label | Value |
| ------------- | ----------- |
| URL to documentation (optional) | https://www.iso.org/committee/53674.html |

## Additional Instructions
```
```

**Comment by lrosenthol** [comment]
Approved
