### ISSUE TITLE
Would like to register 'slns' prefix

### ISSUE THREAD

**Issue by nwilliams-onespan** [adobe/pdf-names-list#11]
# Prefix Registration
## Developer Prefix
| Label | Value |
| ------------- | ----------- |
| Developer Prefix (4 letters) | slns |

## Organization
| Label | Value |
| ------------- | ----------- |
| Entity/Organization Name | OneSpan |
| Address (line 1) | 121 W Wacker Drive, Suite 2050 |
| Address (line 2) | %REPLACE ME% |
| City, State, Zip/Postal Code | 60601 Chicago, IL |
| Country | U.S.A. |
| Web Site/URL | www.onespan.com |

## Person
| Label | Value |
| ------------- | ----------- |
| First Name | Normand |
| Last Name | Williams |
| Title | C++ consultant / Global Cloud Operations & DevOps |
| Email address | normand.williams@onespan.com |

## Optional Documentation Link
| Label | Value |
| ------------- | ----------- |
| URL to documentation (optional) | %REPLACE ME% |

## Additional Instructions
```
// If this form is for updating an existing registration 
// or to instruct Adobe to make a previously private registration public, 
// please note that here
```

**Comment by lrosenthol** [comment]
Approved

**Comment by nwilliams-onespan** [comment]
Wow, this was quick! Thanks, Normand
