### ISSUE TITLE
S4Cx prefix

### ISSUE THREAD

**Issue by Sense4code** [adobe/pdf-names-list#15]
# Prefix Registration
## Developer Prefix
| Label | Value |
| ------------- | ----------- |
| Developer Prefix (4 letters) | S4Cx |

## Organization
| Label | Value |
| ------------- | ----------- |
| Entity/Organization Name | Sense4code s.r.o. |
| Address (line 1) | Rybná 716/24 |
| Address (line 2) |  |
| City, State, Zip/Postal Code | 110 00 Praha |
| Country | Czech Republic |
| Web Site/URL | https://www.sense4code.com/ |

## Person
| Label | Value |
| ------------- | ----------- |
| First Name | Ján |
| Last Name | Hudec |
| Title | CEO & Founder |
| Email address | info@sense4code.com |

## Optional Documentation Link
| Label | Value |
| ------------- | ----------- |
| URL to documentation (optional) |  |

## Additional Instructions
```

```

**Comment by lrosenthol** [comment]
Approved
