### ISSUE TITLE
DMSK prefix

### ISSUE THREAD

**Issue by horvathi** [adobe/pdf-names-list#16]
# Prefix Registration
## Developer Prefix
| Label | Value |
| ------------- | ----------- |
| Developer Prefix (4 letters) | DMSK |

## Organization
| Label | Value |
| ------------- | ----------- |
| Entity/Organization Name | DMS One Zrt. |
| Address (line 1) | Infopark Sétány 1. "I" épület |
| Address (line 2) |  |
| City, State, Zip/Postal Code | 1117, Budapest |
| Country | Hungary |
| Web Site/URL | https://dmsone.hu |

## Person
| Label | Value |
| ------------- | ----------- |
| First Name | István |
| Last Name | Horváth |
| Title | FSD |
| Email address | horvath.istvan@dmsone.hu |

**Comment by lrosenthol** [comment]
Approved
