### ISSUE TITLE
BECI prefix

### ISSUE THREAD

**Issue by jsonn** [adobe/pdf-names-list#18]
# Prefix Registration
## Developer Prefix
| Label | Value |
| ------------- | ----------- |
| Developer Prefix (4 letters) | BECI |

## Organization
| Label | Value |
| ------------- | ----------- |
| Entity/Organization Name | BEC GmbH & Co KG |
| Address (line 1) | Gewerbeallee 19 |
| Address (line 2) | |
| City, State, Zip/Postal Code | Germany, MV, 18107 |
| Country | Germany |
| Web Site/URL | https://www.bec.de |

## Person
| Label | Value |
| ------------- | ----------- |
| First Name | Jörg |
| Last Name | Sonnenberger |
| Title | CTO |
| Email address | joerg@bec.de |

## Optional Documentation Link
| Label | Value |
| ------------- | ----------- |
| URL to documentation (optional) |  |

## Additional Instructions
```
// If this form is for updating an existing registration 
// or to instruct Adobe to make a previously private registration public, 
// please note that here
```

**Comment by lrosenthol** [comment]
Approved
