### ISSUE TITLE
SETA

### ISSUE THREAD

**Issue by JanSlabon** [adobe/pdf-names-list#19]
# Prefix Registration
## Developer Prefix
| Label | Value |
| ------------- | ----------- |
| Developer Prefix (4 letters) | SETA |

## Organization
| Label | Value |
| ------------- | ----------- |
| Entity/Organization Name | Setasign GmbH & Co. KG |
| Address (line 1) | Max-Planck-Weg 7 |
| Address (line 2) |  |
| City, State, Zip/Postal Code | 38350 Helmstedt |
| Country | Germany |
| Web Site/URL | https://www.setasign.com |

## Person
| Label | Value |
| ------------- | ----------- |
| First Name | Jan |
| Last Name | Slabon |
| Title |  |
| Email address | jan.slabon@setasign.com |

## Optional Documentation Link
| Label | Value |
| ------------- | ----------- |
| URL to documentation (optional) |  |

## Additional Instructions
```
This is an update of the existing registration from "Setasign" to "Setasign GmbH & Co. KG"
```

**Comment by lrosenthol** [comment]
Updated

**Comment by JanSlabon** [comment]
@lrosenthol can you please double check this? It looks like we are listed in the [current version](https://github.com/adobe/pdf-names-list/blob/060cb64dfd04618e4f106d10781a6fc6867af8ca/ISO%20PDF%20Registry.xlsx) now two times with the outdated data.
