### ISSUE TITLE
Request to make private developer prefix public

### ISSUE THREAD

**Issue by bertvankerckhove** [adobe/pdf-names-list#23]
# Prefix Registration
## Developer Prefix
| Label | Value |
| ------------- | ----------- |
| Developer Prefix (4 letters) | FICL |

## Organization
| Label | Value |
| ------------- | ----------- |
| Entity/Organization Name | Enfocus BV |
| Address (line 1) | Kortrijksesteenweg 1095 |
| Address (line 2) | %REPLACE ME% |
| City, State, Zip/Postal Code | 9051 Gent |
| Country | Belgium |
| Web Site/URL | http://www.enfocus.com |

## Person
| Label | Value |
| ------------- | ----------- |
| First Name | Bert |
| Last Name | Van Kerckhove |
| Title | Technical expert |
| Email address | bertvk@enfocus.com |

## Optional Documentation Link
| Label | Value |
| ------------- | ----------- |
| URL to documentation (optional) | %REPLACE ME% |

## Additional Instructions

This is a request to make a previously private registration public.

**Comment by petervwyatt** [comment]
@bertvankerckhove please see your email

**Comment by petervwyatt** [comment]
Resolved with commit https://github.com/adobe/pdf-names-list/commit/5165874f69f23f13452bb8ffc64eaed229b79d5a
