### ISSUE TITLE
GWG 2nd class name prefix

### ISSUE THREAD

**Issue by Lieven-Plettinck** [adobe/pdf-names-list#24]
# Prefix Registration
## Developer Prefix
| Label | Value |
| ------------- | ----------- |
| Developer Prefix (4 letters) | GWG_ |

## Organization
| Label | Value |
| ------------- | ----------- |
| Entity/Organization Name | Ghent Workgroup |
| Address (line 1) | St Laurentiuslaan 10 |
| Address (line 2) | %REPLACE ME% |
| City, State, Zip/Postal Code | 9041 Gent |
| Country | Belgium |
| Web Site/URL | www.gwg.org |

## Person
| Label | Value |
| ------------- | ----------- |
| First Name | David |
| Last Name | Zwang |
| Title | Chair |
| Email address | david@zwang.com |

## Optional Documentation Link
| Label | Value |
| ------------- | ----------- |
| URL to documentation (optional) | %REPLACE ME% |

## Additional Instructions
```
// If this form is for updating an existing registration 
// or to instruct Adobe to make a previously private registration public, 
// please note that here

If there was already a 2nd class name prefix registered pre-2008, this is request to make it public.
If there is no prefix was registered this is a request to create the new one "GWG_" i.e. 3 letter+underscore.
We understand that with "GWG_" names would be prefixed with "GWG"+2 underscores.

**Comment by Lieven-Plettinck** [comment]
Note: this request was done on behalf of GWG as a result of the GWG meeting of June 2 2021

**Comment by petervwyatt** [comment]
Added in commit https://github.com/adobe/pdf-names-list/commit/26414a6970970e755d63ba21a651ccc7dae17890
