### ISSUE TITLE
disphere Tech Prefix

### ISSUE THREAD

**Issue by mschubertdisphere** [adobe/pdf-names-list#25]
# Prefix Registration
## Developer Prefix
| Label | Value |
| ------------- | ----------- |
| Developer Prefix (4 letters) | diTe |

## Organization
| Label | Value |
| ------------- | ----------- |
| Entity/Organization Name | disphere tech GmbH |
| Address (line 1) | Ungererstr. 112 |
| Address (line 2) |  |
| City, State, Zip/Postal Code | Munich, 80805 |
| Country | Germany |
| Web Site/URL | https://www.disphere.com |

## Person
| Label | Value |
| ------------- | ----------- |
| First Name | Michael |
| Last Name | Schubert |
| Title |  |
| Email address | m.schubert@disphere.com |

## Optional Documentation Link
| Label | Value |
| ------------- | ----------- |
| URL to documentation (optional) |  |

## Additional Instructions
```
// If this form is for updating an existing registration 
// or to instruct Adobe to make a previously private registration public, 
// please note that here
```

**Comment by petervwyatt** [comment]
Added in commit https://github.com/adobe/pdf-names-list/commit/26414a6970970e755d63ba21a651ccc7dae17890
