### ISSUE TITLE
Provide the list in an alternative document format

### ISSUE THREAD

**Issue by Lonzak** [adobe/pdf-names-list#27]
Currently the list is only provided as a proprietary document format which many people do not have.
There are much better (e.g. ISO standardized) alternative document formats out there :-)

It would be great if an additional (or replacement) document format could be offered. (e.g. csv, pdf, ...)

Thank you!

**Comment by lrosenthol** [comment]
Actually XLSX is an ISO standardized file format.

**Comment by Lonzak** [comment]
Huh you are right: [ISO/IEC29500-1:2016] I stand corrected.
Didn't know that! Always associated the file ending with the product of some company...

Would still be nice to have an alternative file type for the list...
