### ISSUE TITLE
TST_ prefix for TargetStream

### ISSUE THREAD

**Issue by willkil** [adobe/pdf-names-list#37]
# Prefix Registration
## Developer Prefix
| Label | Value |
| ------------- | ----------- |
| Developer Prefix (4 letters) | TST_ |

## Organization
| Label | Value |
| ------------- | ----------- |
| Entity/Organization Name | TargetStream Technologies, Inc. |
| Address (line 1) | 119 N. Parker #161 |
| Address (line 2) |  |
| City, State, Zip/Postal Code | Olathe, KS 66061 |
| Country | USA |
| Web Site/URL | targetstream.com |

## Person
| Label | Value |
| ------------- | ----------- |
| First Name | William |
| Last Name | Kilian |
| Title | Software Architect, PDF/UA |
| Email address | pdf-name-registry@targetstream.com |

## Optional Documentation Link
| Label | Value |
| ------------- | ----------- |
| URL to documentation (optional) |  |

## Additional Instructions
```
// If this form is for updating an existing registration 
// or to instruct Adobe to make a previously private registration public, 
// please note that here
```

**Comment by willkil** [comment]
How about `_TST`, @petervwyatt ? We've always used TST as an abbreviation because those are the letters we capitalize in TargetStream Technologies.

**Comment by Lonzak** [comment]
How about TSTI - TargetStreamTechnologies Inc?
Or TAST / TSTT / TSTE / TSTC ...

**Comment by petervwyatt** [comment]
No - we don't want leading underscores. How about TSTi or TSTI?

**Comment by willkil** [comment]
What a fun game! :) I feel obligated to point out there is already a name registered with a leading underscore, but if that’s not allowed anymore, we still like our original request of `TST_`. We’re not concerned about issues with double underscore.

**Comment by willkil** [comment]
I forgot about this. If we can't get underscores, our next preference is `TSTc`.
