### ISSUE TITLE
PDFA

### ISSUE THREAD

**Issue by DuffJohnson** [adobe/pdf-names-list#5]
# Prefix Registration
## Developer Prefix
| Label | Value |
| ------------- | ----------- |
| Developer Prefix (4 letters) | PDFA |

## Organization
| Label | Value |
| ------------- | ----------- |
| Entity/Organization Name | PDF Association |
| Address (line 1) | Neue Kantstrasse 14 |
| City, State, Zip/Postal Code | 14057 Berlin |
| Country | Germany |
| Web Site/URL | https://pdfa.org |

## Person
| Label | Value |
| ------------- | ----------- |
| First Name | Duff |
| Last Name | Johnson |
| Title | Executive Director |
| Email address | duff.johnson@pdfa.org |

## Additional Instructions
```
// If this form is for updating an existing registration 
// or to instruct Adobe to make a previously private registration public, 
// please note that here
```

**Comment by lrosenthol** [comment]
Unfortunately, the `PDFA` prefix has already been registered.  Please select another option - perhaps the lowercase version, `pdfa`?

**Comment by DuffJohnson** [comment]
OK... we'll take the lowercase version, thanks.
Interesting... I did not know that case was respected per se - Annex E is (was) silent on that. I've just added a note to the draft PW and I are working on. :-)

**Comment by lrosenthol** [comment]
Registration as `pdfa` complete.

**Comment by DuffJohnson** [comment]
Duh. 
OK, thanks!

**Comment by Lonzak** [comment]
> Unfortunately, the PDFA prefix has already been registered. Please select another option - perhaps the lowercase version, pdfa?

@lrosenthol I couldn't find "PDFA" in the list - where and to whom was it registered?

**Comment by DuffJohnson** [comment]
@Lonzak, the new request is for "PDFa", not "PDFA".

Regarding "PDFA", Adobe maintains a list of extensions that were established prior to ISO standardization. These cannot be specifically disclosed due to legal agreements Adobe entered at the time.
